"""
Entity metadata for Presidio supported entities.

Each entity has:
- title: Human-friendly name
- description: What the entity represents
- category: Logical grouping
- domain: Business/security domain
- severity: Relative privacy/security risk (Low/Medium/High/Critical)
- recommended_action: Suggested mitigation
- link: Optional reference URL (when available)
"""

from typing import Dict

# Base defaults used when an entity is not explicitly defined below.
DEFAULT_METADATA = {
    "category": "PII",
    "domain": "DSPM",
    "severity": "Medium",
    "recommended_action": "Mask, anonymize, or avoid storing this data in plaintext.",
    "link": "",
}

# Keys must match Presidio entity_type values.
ENTITY_METADATA: Dict[str, Dict[str, str]] = {
    "ABA_ROUTING_NUMBER": {
        "title": "ABA Routing Number",
        "description": "US bank routing number identifying a financial institution.",
        "category": "Financial",
        "domain": "Banking",
        "severity": "High",
        "recommended_action": "Mask or tokenize; restrict exposure and storage.",
        "link": "https://en.wikipedia.org/wiki/Routing_transit_number",
    },
    "AGE": {
        "title": "Age",
        "description": "An individual's age or age range.",
        "category": "Demographic",
        "domain": "Privacy",
        "severity": "Low",
        "recommended_action": "Generalize or bucketize (e.g., 30-39) where possible.",
        "link": "",
    },
    "AU_ABN": {
        "title": "Australia ABN",
        "description": "Australian Business Number used to identify businesses.",
        "category": "Government ID",
        "domain": "Compliance",
        "severity": "Medium",
        "recommended_action": "Mask or store only when required; limit sharing.",
        "link": "https://abr.business.gov.au/Help/AbnFormat",
    },
    "AU_ACN": {
        "title": "Australia ACN",
        "description": "Australian Company Number assigned by ASIC.",
        "category": "Government ID",
        "domain": "Compliance",
        "severity": "Medium",
        "recommended_action": "Mask or store only when required; limit sharing.",
        "link": "https://asic.gov.au/for-business/starting-a-company/company-structure/company-name/acn/",
    },
    "AU_MEDICARE": {
        "title": "Australia Medicare Number",
        "description": "Australian Medicare card number used for healthcare services.",
        "category": "Health",
        "domain": "Healthcare",
        "severity": "High",
        "recommended_action": "Treat as sensitive health data; mask or tokenize.",
        "link": "",
    },
    "AU_TFN": {
        "title": "Australia TFN",
        "description": "Australian Tax File Number used for taxation purposes.",
        "category": "Government ID",
        "domain": "Taxation",
        "severity": "High",
        "recommended_action": "Mask, encrypt, or tokenize; restrict access.",
        "link": "https://www.ato.gov.au/Individuals/Tax-file-number/",
    },
    "CREDIT_CARD": {
        "title": "Credit Card Number",
        "description": "Payment card number (e.g., VISA, Mastercard).",
        "category": "Financial",
        "domain": "Payments",
        "severity": "Critical",
        "recommended_action": "Do not log; tokenize; store only per PCI DSS requirements.",
        "link": "https://www.pcisecuritystandards.org/",
        "detection_method": "Pattern match and checksum",
    },
    "CRYPTO": {
        "title": "Cryptocurrency Wallet Address",
        "description": "A Crypto wallet number. Currently only Bitcoin address is supported",
        "category": "Financial",
        "domain": "Blockchain",
        "severity": "Medium",
        "recommended_action": "Avoid exposing; mask or truncate where feasible.",
        "link": "",
        "detection_method": "Pattern match, context and checksum",
    },
    "DATE_TIME": {
        "title": "Date/Time",
        "description": "Absolute or relative dates or periods or times smaller than a day.",
        "category": "Temporal",
        "domain": "Privacy",
        "severity": "Low",
        "recommended_action": "Reduce precision (e.g., day to month) if not needed.",
        "link": "",
        "detection_method": "Pattern match and context",
    },
    "EMAIL": {
        "title": "Email (Free Text)",
        "description": "An email value extracted by language models.",
        "category": "Contact",
        "domain": "Communications",
        "severity": "Medium",
        "recommended_action": "Mask local-part; avoid logging unredacted emails.",
        "link": "",
    },
    "EMAIL_ADDRESS": {
        "title": "Email Address",
        "description": "An email address identifies an email box to which email messages are delivered",
        "category": "Contact",
        "domain": "Communications",
        "severity": "Medium",
        "recommended_action": "Mask local-part or hash; avoid logging.",
        "link": "https://en.wikipedia.org/wiki/Email_address",
        "detection_method": "Pattern match, context and RFC-822 validation",
    },
    "ES_NIE": {
        "title": "Spain NIE",
        "description": "Número de Identidad de Extranjero for foreign nationals in Spain.",
        "category": "Government ID",
        "domain": "Compliance",
        "severity": "High",
        "recommended_action": "Mask or tokenize; restrict access.",
        "link": "",
        "detection_method": "Pattern match, context and checksum",
    },
    "ES_NIF": {
        "title": "Spain NIF",
        "description": "Número de Identificación Fiscal (tax identification number).",
        "category": "Government ID",
        "domain": "Taxation",
        "severity": "High",
        "recommended_action": "Mask or tokenize; restrict access.",
        "link": "",
        "detection_method": "Pattern match, context and checksum",
    },
    "FI_PERSONAL_IDENTITY_CODE": {
        "title": "Finland Personal Identity Code",
        "description": "Finnish national identification number.",
        "category": "Government ID",
        "domain": "Compliance",
        "severity": "High",
        "recommended_action": "Mask or tokenize; restrict access.",
        "link": "",
        "detection_method": "Pattern match, context and custom logic.",
    },
    "IBAN_CODE": {
        "title": "IBAN",
        "description": "The International Bank Account Number (IBAN) is an internationally agreed system of identifying bank accounts across national borders to facilitate the communication and processing of cross border transactions with a reduced risk of transcription errors.",
        "category": "Financial",
        "domain": "Banking",
        "severity": "High",
        "recommended_action": "Mask or tokenize; store per banking standards.",
        "link": "https://en.wikipedia.org/wiki/International_Bank_Account_Number",
        "detection_method": "Pattern match, context and checksum",
    },
    "ID": {
        "title": "Identifier (Generic)",
        "description": "A generic identifier detected by language models.",
        "category": "Identifier",
        "domain": "Privacy",
        "severity": "Low",
        "recommended_action": "Review case-by-case; mask if it links to a person.",
        "link": "",
    },
    "IN_AADHAAR": {
        "title": "India Aadhaar Number",
        "description": "Indian government issued unique 12 digit individual identity number",
        "category": "Government ID",
        "domain": "Compliance",
        "severity": "High",
        "recommended_action": "Mask, encrypt, or tokenize; follow Indian privacy laws.",
        "link": "https://uidai.gov.in/",
        "detection_method": "Pattern match, context, and checksum",
    },
    "IN_GSTIN": {
        "title": "India GSTIN",
        "description": "The Indian Goods and Services Tax Identification Number (GSTIN) is a 15-character identifier with state code (01-37), PAN, registration number, 'Z', and checksum.",
        "category": "Tax ID",
        "domain": "Taxation",
        "severity": "Medium",
        "recommended_action": "Mask or tokenize; restrict access.",
        "link": "",
        "detection_method": "Pattern match, context, and validation",
    },
    "IN_PAN": {
        "title": "India PAN",
        "description": "The Indian Permanent Account Number (PAN) is a unique 12 character alphanumeric identifier issued to all business and individual entities registered as Tax Payers.",
        "category": "Tax ID",
        "domain": "Taxation",
        "severity": "High",
        "recommended_action": "Mask or tokenize; restrict access.",
        "link": "",
        "detection_method": "Pattern match, context",
    },
    "IN_PASSPORT": {
        "title": "India Passport Number",
        "description": "Indian Passport Number",
        "category": "Government ID",
        "domain": "Travel",
        "severity": "High",
        "recommended_action": "Mask or tokenize; restrict access.",
        "link": "",
        "detection_method": "Pattern match, context",
    },
    "IN_VEHICLE_REGISTRATION": {
        "title": "India Vehicle Registration",
        "description": "Indian government issued transport (govt, personal, diplomatic, defence)  vehicle registration number",
        "category": "Identifier",
        "domain": "Transport",
        "severity": "Low",
        "recommended_action": "Mask or truncate where feasible.",
        "link": "",
        "detection_method": "Pattern match, context, and checksum",
    },
    "IN_VOTER": {
        "title": "India Voter ID",
        "description": "Indian Election Commission issued 10 digit alpha numeric voter id for all indian citizens (age 18 or above)",
        "category": "Government ID",
        "domain": "Compliance",
        "severity": "High",
        "recommended_action": "Mask or tokenize; restrict access.",
        "link": "",
        "detection_method": "Pattern match, context",
    },
    "IP_ADDRESS": {
        "title": "IP Address",
        "description": "An Internet Protocol (IP) address (either IPv4 or IPv6).",
        "category": "Network",
        "domain": "Security",
        "severity": "Medium",
        "recommended_action": "Avoid logging full IPs; mask or hash if needed.",
        "link": "https://en.wikipedia.org/wiki/IP_address",
        "detection_method": "Pattern match, context and checksum",
    },
    "IT_DRIVER_LICENSE": {
        "title": "Italy Driver's License",
        "description": "Italian driver's license number.",
        "category": "Government ID",
        "domain": "Transport",
        "severity": "High",
        "recommended_action": "Mask or tokenize; restrict access.",
        "link": "",
        "detection_method": "Pattern match and context",
    },
    "IT_FISCAL_CODE": {
        "title": "Italy Fiscal Code",
        "description": "Italian tax code (Codice Fiscale).",
        "category": "Tax ID",
        "domain": "Taxation",
        "severity": "High",
        "recommended_action": "Mask or tokenize; restrict access.",
        "link": "https://en.wikipedia.org/wiki/Italian_fiscal_code",
        "detection_method": "Pattern match, context and checksum",
    },
    "IT_IDENTITY_CARD": {
        "title": "Italy Identity Card",
        "description": "Italian national identity card number.",
        "category": "Government ID",
        "domain": "Compliance",
        "severity": "High",
        "recommended_action": "Mask or tokenize; restrict access.",
        "link": "",
        "detection_method": "Pattern match and context",
    },
    "IT_PASSPORT": {
        "title": "Italy Passport Number",
        "description": "Italian passport identifier.",
        "category": "Government ID",
        "domain": "Travel",
        "severity": "High",
        "recommended_action": "Mask or tokenize; restrict access.",
        "link": "",
        "detection_method": "Pattern match and context",
    },
    "IT_VAT_CODE": {
        "title": "Italy VAT Code",
        "description": "Italian Value Added Tax identification number.",
        "category": "Tax ID",
        "domain": "Taxation",
        "severity": "Medium",
        "recommended_action": "Mask or tokenize; restrict access.",
        "link": "",
        "detection_method": "Pattern match, context and checksum",
    },
    "KR_RRN": {
        "title": "Korea RRN",
        "description": "Korean Resident Registration Number.",
        "category": "Government ID",
        "domain": "Compliance",
        "severity": "High",
        "recommended_action": "Mask, encrypt, or tokenize; restrict access.",
        "link": "",
    },
    "LOCATION": {
        "title": "Location",
        "description": "Name of politically or geographically defined location (cities, provinces, countries, international regions, bodies of water, mountains)",
        "category": "Demographic",
        "domain": "Privacy",
        "severity": "Low",
        "recommended_action": "Reduce precision when possible (e.g., city instead of address).",
        "link": "",
        "detection_method": "Custom logic and context",
    },
    "MEDICAL_LICENSE": {
        "title": "US Medical License Number",
        "description": "Common medical license numbers.",
        "category": "Health",
        "domain": "Healthcare",
        "severity": "High",
        "recommended_action": "Treat as sensitive; mask or tokenize.",
        "link": "",
        "detection_method": "Pattern match, context and checksum",
    },
    "NRP": {
        "title": "NRP",
        "description": "A person’s Nationality, religious or political group.",
        "category": "Annotation",
        "domain": "Privacy",
        "severity": "Low",
        "recommended_action": "Typically no action required.",
        "link": "",
        "detection_method": "Custom logic and context",
    },
    "ORGANIZATION": {
        "title": "Organization",
        "description": "Named organization such as a company or institution.",
        "category": "Entity",
        "domain": "Privacy",
        "severity": "Low",
        "recommended_action": "Mask only if combined with other PII.",
        "link": "",
    },
    "PERSON": {
        "title": "Person",
        "description": "A full person name, which can include first names, middle names or initials, and last names.",
        "category": "Identity",
        "domain": "Privacy",
        "severity": "Medium",
        "recommended_action": "Mask names in logs and analytics outputs.",
        "link": "",
        "detection_method": "Custom logic and context",
    },
    "PHONE_NUMBER": {
        "title": "Phone Number",
        "description": "A telephone number",
        "category": "Contact",
        "domain": "Communications",
        "severity": "Medium",
        "recommended_action": "Mask or hash; avoid storing in plaintext.",
        "link": "",
        "detection_method": "Custom logic, pattern match and context",
    },
    "PL_PESEL": {
        "title": "Poland PESEL",
        "description": "Polish national identification number.",
        "category": "Government ID",
        "domain": "Compliance",
        "severity": "High",
        "recommended_action": "Mask or tokenize; restrict access.",
        "link": "",
        "detection_method": "Pattern match, context and checksum",
    },
    "SG_NRIC_FIN": {
        "title": "Singapore NRIC/FIN",
        "description": "Singapore National Registration Identity Card or Foreign Identification Number.",
        "category": "Government ID",
        "domain": "Compliance",
        "severity": "High",
        "recommended_action": "Mask or tokenize; restrict access.",
        "link": "",
        "detection_method": "Pattern match and context",
    },
    "SG_UEN": {
        "title": "Singapore UEN",
        "description": "Unique Entity Number for Singapore-registered entities.",
        "category": "Government ID",
        "domain": "Compliance",
        "severity": "Medium",
        "recommended_action": "Mask or store only when required; limit sharing.",
        "link": "",
        "detection_method": "Pattern match, context, and checksum",
    },
    "TH_TNIN": {
        "title": "Thailand TNIN",
        "description": "Thai Tax Identification Number.",
        "category": "Tax ID",
        "domain": "Taxation",
        "severity": "High",
        "recommended_action": "Mask or tokenize; restrict access.",
        "link": "",
        "detection_method": "Pattern match, context and custom logic.",
    },
    "UK_NHS": {
        "title": "UK NHS Number",
        "description": "A UK NHS number is 10 digits.",
        "category": "Health",
        "domain": "Healthcare",
        "severity": "High",
        "recommended_action": "Treat as sensitive health data; mask or tokenize.",
        "link": "",
        "detection_method": "Pattern match, context and checksum",
    },
    "UK_NINO": {
        "title": "UK National Insurance Number",
        "description": "UK social security number used for tax and benefits.",
        "category": "Government ID",
        "domain": "Taxation",
        "severity": "High",
        "recommended_action": "Mask, encrypt, or tokenize; restrict access.",
        "link": "https://en.wikipedia.org/wiki/National_Insurance_number",
        "detection_method": "Pattern match and context",
    },
    "URL": {
        "title": "URL",
        "description": "A URL (Uniform Resource Locator), unique identifier used to locate a resource on the Internet",
        "category": "Identifier",
        "domain": "Web",
        "severity": "Low",
        "recommended_action": "Remove query parameters if sensitive; avoid logging secrets.",
        "link": "https://en.wikipedia.org/wiki/URL",
        "detection_method": "Pattern match, context and top level url validation",
    },
    "US_BANK_NUMBER": {
        "title": "US Bank Account Number",
        "description": "A US bank account number is between 8 to 17 digits.",
        "category": "Financial",
        "domain": "Banking",
        "severity": "Critical",
        "recommended_action": "Tokenize; never store or log in plaintext.",
        "link": "",
        "detection_method": "Pattern match and context",
    },
    "US_DRIVER_LICENSE": {
        "title": "US Driver's License",
        "description": "A US driver license according to https://ntsi.com/drivers-license-format/",
        "category": "Government ID",
        "domain": "Transport",
        "severity": "High",
        "recommended_action": "Mask or tokenize; restrict access.",
        "link": "",
        "detection_method": "Pattern match and context",
    },
    "US_ITIN": {
        "title": "US ITIN",
        "description": "US Individual Taxpayer Identification Number (ITIN). Nine digits that start with a \"9\" and contain a \"7\" or \"8\" as the 4 digit.",
        "category": "Tax ID",
        "domain": "Taxation",
        "severity": "High",
        "recommended_action": "Mask or tokenize; restrict access.",
        "link": "",
        "detection_method": "Pattern match and context",
    },
    "US_PASSPORT": {
        "title": "US Passport Number",
        "description": "A US passport number with 9 digits.",
        "category": "Government ID",
        "domain": "Travel",
        "severity": "High",
        "recommended_action": "Mask or tokenize; restrict access.",
        "link": "",
        "detection_method": "Pattern match and context",
    },
    "US_SSN": {
        "title": "US Social Security Number",
        "description": "A US Social Security Number (SSN) with 9 digits.",
        "category": "Government ID",
        "domain": "Compliance",
        "severity": "Critical",
        "recommended_action": "Tokenize; never log; restrict and monitor access.",
        "link": "https://www.ssa.gov/ssnumber/",
        "detection_method": "Pattern match and context",
    },
}


def _auto_title(entity_type: str) -> str:
    return entity_type.replace("_", " ").title() if entity_type else "Unknown"


def get_entity_metadata(entity_type: str) -> Dict[str, str]:
    """
    Return metadata for the requested entity_type.
    Falls back to generated title/description and DEFAULT_METADATA if not explicitly defined.
    """
    meta = ENTITY_METADATA.get(entity_type, {})
    if meta:
        # Ensure domain aligns with DSPM consistently
        meta_out = dict(meta)
        meta_out["domain"] = "DSPM"
        return meta_out
    # Build a sensible fallback
    title = _auto_title(entity_type)
    description = f"{title} detected by Presidio."
    fallback = dict(DEFAULT_METADATA)
    fallback.update({"title": title, "description": description})
    return fallback

